// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Recibo.Models;

public partial class Ato
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public decimal CustasOficial { get; set; }

    public decimal CustasIss { get; set; }

    public decimal CustasIpesp { get; set; }

    public string Descricao { get; set; }

    public virtual ICollection<ReciboAto> ReciboAtos { get; set; } = new List<ReciboAto>();

    public virtual ICollection<ReciboProvisorioAto> ReciboProvisorioAtos { get; set; } = new List<ReciboProvisorioAto>();
}