// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Recibo.Models;

[Table("recibos")]
[Index("ReciboProvisorioId", Name = "recibo_provisorio_id")]
public partial class ReciboDefinitivo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("data", TypeName = "timestamp")]
    public DateTime? Data { get; set; }

    [Required]
    [Column("requerente")]
    [StringLength(255)]
    public string Requerente { get; set; }

    [Column("recibo_provisorio_id")]
    public int? ReciboProvisorioId { get; set; }

    [Column("cpf")]
    [StringLength(11)]
    public string Cpf { get; set; }

    [NotMapped]
    public decimal Total => ReciboAtos.Sum(a => a.Total);

    [InverseProperty("Recibo")]
    public virtual ICollection<ReciboAto> ReciboAtos { get; set; } = new List<ReciboAto>();

    [ForeignKey("ReciboProvisorioId")]
    [InverseProperty("Recibos")]
    public virtual ReciboProvisorio ReciboProvisorio { get; set; }
}