// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Recibo.Models;

public partial class ReciboAto
{
    public int ReciboId { get; set; }

    public int AtoId { get; set; }

    public string Descricao { get; set; }

    public int Quantidade { get; set; }

    public virtual Ato Ato { get; set; }

    public virtual ReciboDefinitivo Recibo { get; set; }
}