// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Recibo.Models;

public partial class ReciboProvisorio
{
    public int Id { get; set; }

    public DateTime? Data { get; set; }

    public string Requerente { get; set; }

    public virtual ICollection<ReciboProvisorioAto> ReciboProvisorioAtos { get; set; } = new List<ReciboProvisorioAto>();

    public virtual ICollection<ReciboDefinitivo> Recibos { get; set; } = new List<ReciboDefinitivo>();
}