// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal;

namespace Recibo.Models;

public partial class recibos_dbContext : DbContext
{
    public recibos_dbContext()
    {
    }

    public recibos_dbContext(DbContextOptions<recibos_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ato> Atos { get; set; }

    public virtual DbSet<ReciboDefinitivo> Recibos { get; set; }

    public virtual DbSet<ReciboAto> ReciboAtos { get; set; }

    public virtual DbSet<ReciboProvisorioAto> ReciboProvisorioAtos { get; set; }

    public virtual DbSet<ReciboProvisorio> RecibosProvisorios { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseMySql("server=localhost;port=3307;database=recibos_db;uid=root;pwd=secret", Microsoft.EntityFrameworkCore.ServerVersion.Parse("8.0.39-mysql"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Ato>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");
            entity.Property(e => e.Codigo).IsFixedLength();
        });

        modelBuilder.Entity<ReciboDefinitivo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");
            entity.Property(e => e.Data)
                  .HasDefaultValueSql("CURRENT_TIMESTAMP")
                  .HasConversion(
                      v => v,
                      v => DateTime.SpecifyKind((DateTime)v, DateTimeKind.Local));
            entity.HasOne(d => d.ReciboProvisorio).WithMany(p => p.Recibos).HasConstraintName("recibos_ibfk_1");
        });

        modelBuilder.Entity<ReciboAto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");
            entity.HasOne(d => d.Ato).WithMany(p => p.ReciboAtos)
                  .OnDelete(DeleteBehavior.Cascade)
                  .HasConstraintName("recibo_atos_ibfk_2");
            entity.HasOne(d => d.Recibo).WithMany(p => p.ReciboAtos)
                  .OnDelete(DeleteBehavior.Cascade)
                  .HasConstraintName("recibo_atos_ibfk_1");
        });

        modelBuilder.Entity<ReciboProvisorioAto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");
            entity.HasOne(d => d.Ato).WithMany(p => p.ReciboProvisorioAtos)
                  .OnDelete(DeleteBehavior.Cascade)
                  .HasConstraintName("recibo_provisorio_atos_ibfk_2");
            entity.HasOne(d => d.ReciboProvisorio).WithMany(p => p.ReciboProvisorioAtos)
                  .OnDelete(DeleteBehavior.Cascade)
                  .HasConstraintName("recibo_provisorio_atos_ibfk_1");
        });

        modelBuilder.Entity<ReciboProvisorio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");
            entity.Property(e => e.Data)
                  .HasDefaultValueSql("CURRENT_TIMESTAMP")
                  .HasConversion(
                      v => v,
                      v => DateTime.SpecifyKind((DateTime)v, DateTimeKind.Local));
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}