// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Recibo.Models;

[Table("recibo_atos")]
[Index("AtoId", Name = "ato_id")]
[Index("ReciboId", Name = "recibo_id")]
public partial class ReciboAto
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("recibo_id")]
    public int? ReciboId { get; set; }

    [Column("ato_id")]
    public int? AtoId { get; set; }

    [Column("descricao")]
    [StringLength(127)]
    public string Descricao { get; set; }

    [Column("quantidade")]
    public int Quantidade { get; set; }

    [ForeignKey("AtoId")]
    [InverseProperty("ReciboAtos")]
    public virtual Ato Ato { get; set; }

    [ForeignKey("ReciboId")]
    [InverseProperty("ReciboAtos")]
    public virtual ReciboDefinitivo Recibo { get; set; }
}