// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Recibo.Models;

public partial class ReciboDefinitivo
{
    public int Id { get; set; }

    public DateTime? Data { get; set; }

    public string Requerente { get; set; }

    public int? ReciboProvisorioId { get; set; }

    public virtual ICollection<ReciboAto> ReciboAtos { get; set; } = new List<ReciboAto>();

    public virtual ReciboProvisorio ReciboProvisorio { get; set; }
}