// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Recibo.Models;

public partial class recibos_dbContext : DbContext
{
    public recibos_dbContext(DbContextOptions<recibos_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ato> Atos { get; set; }

    public virtual DbSet<ReciboDefinitivo> Recibos { get; set; }

    public virtual DbSet<ReciboAto> ReciboAtos { get; set; }

    public virtual DbSet<ReciboProvisorioAto> ReciboProvisorioAtos { get; set; }

    public virtual DbSet<ReciboProvisorio> RecibosProvisorios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Ato>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("atos");

            entity.HasIndex(e => e.Nome, "nome").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CustasIpesp)
                .HasPrecision(10, 2)
                .HasColumnName("custas_ipesp");
            entity.Property(e => e.CustasIss)
                .HasPrecision(10, 2)
                .HasColumnName("custas_iss");
            entity.Property(e => e.CustasOficial)
                .HasPrecision(10, 2)
                .HasColumnName("custas_oficial");
            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(63)
                .HasColumnName("descricao");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("nome");
        });

        modelBuilder.Entity<ReciboDefinitivo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("recibos");

            entity.HasIndex(e => e.ReciboProvisorioId, "recibo_provisorio_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Data)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("data");
            entity.Property(e => e.ReciboProvisorioId).HasColumnName("recibo_provisorio_id");
            entity.Property(e => e.Requerente)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("requerente");

            entity.HasOne(d => d.ReciboProvisorio).WithMany(p => p.Recibos)
                .HasForeignKey(d => d.ReciboProvisorioId)
                .HasConstraintName("recibos_ibfk_1");
        });

        modelBuilder.Entity<ReciboAto>(entity =>
        {
            entity.HasKey(e => new { e.ReciboId, e.AtoId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("recibo_atos");

            entity.HasIndex(e => e.AtoId, "ato_id");

            entity.Property(e => e.ReciboId).HasColumnName("recibo_id");
            entity.Property(e => e.AtoId).HasColumnName("ato_id");
            entity.Property(e => e.Descricao)
                .HasMaxLength(127)
                .HasColumnName("descricao");
            entity.Property(e => e.Quantidade).HasColumnName("quantidade");

            entity.HasOne(d => d.Ato).WithMany(p => p.ReciboAtos)
                .HasForeignKey(d => d.AtoId)
                .HasConstraintName("recibo_atos_ibfk_2");

            entity.HasOne(d => d.Recibo).WithMany(p => p.ReciboAtos)
                .HasForeignKey(d => d.ReciboId)
                .HasConstraintName("recibo_atos_ibfk_1");
        });

        modelBuilder.Entity<ReciboProvisorioAto>(entity =>
        {
            entity.HasKey(e => new { e.ReciboProvisorioId, e.AtoId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("recibo_provisorio_atos");

            entity.HasIndex(e => e.AtoId, "ato_id");

            entity.Property(e => e.ReciboProvisorioId).HasColumnName("recibo_provisorio_id");
            entity.Property(e => e.AtoId).HasColumnName("ato_id");
            entity.Property(e => e.Descricao)
                .HasMaxLength(127)
                .HasColumnName("descricao");
            entity.Property(e => e.Quantidade).HasColumnName("quantidade");

            entity.HasOne(d => d.Ato).WithMany(p => p.ReciboProvisorioAtos)
                .HasForeignKey(d => d.AtoId)
                .HasConstraintName("recibo_provisorio_atos_ibfk_2");

            entity.HasOne(d => d.ReciboProvisorio).WithMany(p => p.ReciboProvisorioAtos)
                .HasForeignKey(d => d.ReciboProvisorioId)
                .HasConstraintName("recibo_provisorio_atos_ibfk_1");
        });

        modelBuilder.Entity<ReciboProvisorio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("recibos_provisorios");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Data)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("data");
            entity.Property(e => e.Requerente)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("requerente");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}